omni_management:
  outputs:
    dev:
      dbname: root
      host: localhost
      pass: root
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: root
  target: dev
omnimanagement:
  outputs:
    dev:
      dbname: root
      host: localhost
      password: root
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: root
  target: dev
